apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: kkk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kkk
  template:
    metadata:
      labels:
        app: kkk
    spec:
      containers:
      - name: kkk
        image: aditya75288/kkk:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: kkk
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
